### ISSUE TITLE
[BUG] Project scaffolding doesn't work with go module name that contains special character `-`

### ISSUE THREAD

**Issue by rfinner** [appable-run/appy#131]
**Description**

`go run . setup` has many warnings and fails on `syntax error: pkg/graphql/generated/generated.go:2204:44: syntax error: unexpected -, expecting ( pkg/graphql/generated/generated.go:2208:6: missing function body`.

**Steps To Reproduce**

1. Performed Step 1, 2 and 3 of Quickstart
2. Error occurs on Step 4: go run . setup
3. MySql was selected
4. Project/Module name was "go-fishee"
5. I closely followed instructions with no customizations

I am excited about this project and I look forward to making this work. Thanks!

**Environment**

- OS: Ubuntu 20.04 with latest updates
- node -v: v14.7.0
- go version go1.14.6 linux/amd64

**Additional Information**

go.mod
```go
module go-fishee

go 1.14

require (
	github.com/99designs/gqlgen v0.11.3
	github.com/appist/appy v0.1.1
	github.com/vektah/gqlparser/v2 v2.0.1
)
```

**Comment by rfinner** [comment]
It looks like the function name generated has special characters or something:

func (ec *executionContext) marshalNTodo2ᚕᚖgo-fisheeᚋpkgᚋgraphqlᚋmodelᚐTodoᚄ(ctx context.Context, sel ast.SelectionSet, v []*model.Todo) graphql.Marshaler {

**Comment by rfinner** [comment]
module go-fishee

go 1.14

require (
	github.com/99designs/gqlgen v0.11.3
	github.com/appist/appy v0.1.1
	github.com/vektah/gqlparser/v2 v2.0.1
)

**Comment by cayter** [comment]
@rfinner I am able to reproduce this and this appears to be a very unfortunate case which [gqlgen](https://gqlgen.com/) auto code generation doesn't play well with module name that contains `-`. As a matter of fact, golang does have [an idiomatic way](https://blog.golang.org/package-names) for naming package/module names which means you should name your module name as `gofishee`. Thanks.

**Comment by cayter** [comment]
@rfinner 

I am able to reproduce this and this appears to be a very unfortunate case which [gqlgen](https://gqlgen.com/) auto code generation doesn't play well with module name that contains `-`. As a matter of fact, golang does have [an idiomatic way](https://blog.golang.org/package-names) for naming package/module names which means you should name your module name as `gofishee`. To prevent anyone else from bumping into the same issue, I am gonna update the README.md to remind people. Thanks for reporting the issue though!

**Comment by rfinner** [comment]
That is great news for me and I will update my module name as requested. Thanks for the speedy response!
