### ISSUE TITLE
[BUG] go run . setup returns ERROR Version in "None" is unsupported

### ISSUE THREAD

**Issue by rfinner** [appable-run/appy#134]
**Description**

`go run . setup` returns the error below:

```bash
ERROR: Version in "None" is unsupported. You might be seeing this error because you're using the wrong Compose file version. Either specify a supported version (e.g "2.2" or "3.3") and place your service definitions under the `services` key, or omit the `version` key and place your service definitions at the root of the file to use version 1.
For more on the Compose file format versions, see https://docs.docker.com/compose/compose-file/
2020-08-04T11:04:51.627-0700	FATAL	exit status 1
github.com/appist/appy/cmd.newSetupCommand.func1
	/home/rob/go/pkg/mod/github.com/appist/appy@v0.1.1/cmd/setup.go:30
github.com/spf13/cobra.(*Command).execute
	/home/rob/go/pkg/mod/github.com/spf13/cobra@v1.0.0/command.go:846
github.com/spf13/cobra.(*Command).ExecuteC
	/home/rob/go/pkg/mod/github.com/spf13/cobra@v1.0.0/command.go:950
github.com/spf13/cobra.(*Command).Execute
	/home/rob/go/pkg/mod/github.com/spf13/cobra@v1.0.0/command.go:887
github.com/appist/appy.(*App).Run
	/home/rob/go/pkg/mod/github.com/appist/appy@v0.1.1/app.go:109
gofishee/pkg/app.Run
	/home/rob/dv/go/gofishee/pkg/app/app.go:104
main.main
	/home/rob/dv/go/gofishee/main.go:28
runtime.main
	/home/linuxbrew/.linuxbrew/Cellar/go/1.14.6/libexec/src/runtime/proc.go:203
exit status 1
```

**Steps To Reproduce**

1. Went through the setup steps with `mysql` selected and name the project as `gofishee`
2. Run `go run . setup`

**Comment by cayter** [comment]
@rfinner Could you also paste your `docker-compose.yml` here? Also, what's your docker and docker-compose version? Thanks.

**Comment by cayter** [comment]
@rfinner 

Could you also paste your `docker-compose.yml` here? Also, what's your docker and docker-compose version? Thanks.

**Comment by cayter** [comment]
@rfinner 

What's your docker and docker-compose version? I did a quick search and there are ppl facing the same issue [here](https://github.com/10up/wp-local-docker/issues/58) when `docker-compose < 1.13.0` as the generated `docker-compose.yml` defines version as `3.8` which would need `docker-compose >= 1.13.0`. Thanks.

**Comment by rfinner** [comment]
You were correct. This was not an appy bug at all. The docker compose I had installed was broken for everything. I removed docker-compose 1.25 on ubuntu 20.04 and installed docker-compose 1.26.2 using the instructions on the docker site and everything works great now. Your framework looks great and I am learning much from it. Thanks!
